### ISSUE TITLE
systemctl: not found

### ISSUE THREAD

**Issue by Baldrax** [aaronsmithtv/Houdini-Docker#14]
I am new to docker, so I'm not sure if I've done something wrong in the setup.

I've followed the step-by-step to get this running and as I attempt to run the hserver command in step 5, using my credentials, I get the following error:
> `sh: 1: systemctl: not found`

I get the same error if I just run `hserver` without any arguments.

I built the image with the latest Houdini build which is 20.5.332

**Comment by KevinCalderone** [comment]
I see that error too but it doesn't seem to be causing any issues from what I can tell. So I have just been ignoring it for now 🤷

**Comment by Baldrax** [comment]
> I see that error too but it doesn't seem to be causing any issues from what I can tell. So I have just been ignoring it for now 🤷

Oh, you were able to get a license? Mine wasn't acquiring my license so I thought that was to blame, I'll revisit the licensing step, perhaps I wasn't doing it correctly.

**Comment by KevinCalderone** [comment]
Yeah I do have licenses working properly with the latest image. (20.5.332)

We have things setup slightly differently than the readme in this repo. What we do:
1. Write the ClientID/ClientSecret into the "/root/houdini20.5/hserver.ini" file. The syntax of that:
ClientID=xxxxxxx
ClientSecret=xxxxxxxx
2. Run "hserver -S https://www.sidefx.com/license/sesinetd"
3. Run "hython" with the desired script

There was a discussion of whether the hserver command need to use "--host" or "-S". I am not quite sure what the "correct" method is: https://github.com/aaronsmithtv/Houdini-Docker/issues/11

**Comment by Baldrax** [comment]
Thanks, I'll consider your alternate method.

This time when I ran it like in the readme it found my license, I'm not sure what was going on before.
So I guess this issue wasn't an issue, likely some user error.
